import { promises as fs } from 'fs'
import type Context from './Context'

export async function generateDeclaration(ctx: Context, filePath: string) {
  //   const body = [
  //     ...Object.entries(imports),
  //     ...Object.entries(resolvedImports)
  //   ]
  //     .sort((a, b) => a[0].localeCompare(b[0]))
  //     .map(([name, info]) => `  const ${name}: typeof import('${info.path}')${info.importName !== '*' ? `['${info.importName || name}']` : ''}`)
  //     .join('\n')

  const body = 'const Logo: typeof import(\'./assets/images/logo.png\')[\'default\']'
  const dtsCode = `// Generated by 'unplugin-vue-images'
// We suggest you to commit this file into source control
declare global {
  ${body}
}

export {}
`
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  await fs.writeFile(filePath, dtsCode, 'utf-8')
}
