// Generated by 'unplugin-vue-image'
// We suggest you to commit this file into source control
declare global {
  const Abc: typeof import('/src/assets/images/abc.png')['default']
  const Logo: typeof import('/src/assets/images/logo.png')['default']
}

export {}
